import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center  p-24">
          <h1 className="font-bold text-3xl pb-3">
            TheMealDB API
          </h1>
          <div className="flex gap-3">{children}</div>
        </main>
      </body>
    </html>
  )
}
